---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- Media:
    - Plex:
        icon: plex.png
        href: "https://{{HOMEPAGE_VAR_HomeserverURL}}:32400/web"

        description: Plex Media Management
        ping: {{HOMEPAGE_VAR_HomeserverURL}}
        widget:
          type: plex 
          url: "https://{{HOMEPAGE_VAR_HomeserverURL}}:32400"
          key: {{HOMEPAGE_VAR_PlexAPI}}
    - Sonarr:
        icon: sonarr.png
        href: "http://{{HOMEPAGE_VAR_DockerURL}}:8989"
        description: TV Series Management
        ping: "{{HOMEPAGE_VAR_DockerURL}}:8989"
        widget:
          type: sonarr
          url: "http://{{HOMEPAGE_VAR_DockerURL}}:8989"
          key: {{HOMEPAGE_VAR_SonarrAPI}}
    - Radarr:
        icon: radarr.png
        href: "http://{{HOMEPAGE_VAR_DockerURL}}:7878"
        description: Movie Management
        ping: "{{HOMEPAGE_VAR_DockerURL}}:7878"
        widget:
          type: radarr
          url: "http://{{HOMEPAGE_VAR_DockerURL}}:7878"
          key: {{HOMEPAGE_VAR_RadarrAPI}}
    - lidarr:
        icon: lidarr.png
        href: "http://{{HOMEPAGE_VAR_DockerURL}}:8686"
        description: Music Management
        ping: "{{HOMEPAGE_VAR_DockerURL}}:8686"
        widget:
          type: lidarr
          url: "http://{{HOMEPAGE_VAR_DockerURL}}:8686"
          key: {{HOMEPAGE_VAR_LidarrAPI}}
    - sabnzb:
        icon: /icons/sabnzb.png
        href: "http://{{HOMEPAGE_VAR_DockerURL}}:8080"
        description: NZB Download Management
        ping: "{{HOMEPAGE_VAR_DockerURL}}:8080"
        widget:
          type: sabnzbd
          url: "http://{{HOMEPAGE_VAR_DockerURL}}:8080"
          key: {{HOMEPAGE_VAR_SabnzbAPI}}



- Admin Console:

    - Xen Orchestrator:
        icon: /icons/xo.png
        href: "https://{{HOMEPAGE_VAR_XOURL}}/signin#/"
        description: XO VM management
        ping: {{HOMEPAGE_VAR_XOURL}}

    - XCP-NG1:
        icon: /icons/xcp-ng.png
        href: "https://{{HOMEPAGE_VAR_XCPNG1URL}}/#/"
        description: XCP-NG1 VM Host
        ping: {{HOMEPAGE_VAR_XCPNG1URL}}

    - Homeassistant:
        icon: /icons/ha.png
        href: "https://{{HOMEPAGE_VAR_HomeAssistantURL}}:8123"
        description: Home Assistant - Home Automation
        ping: {{HOMEPAGE_VAR_HomeAssistantURL}}
       # widget:
       #   type: homeassistant
       #   url: "https://{{HOMEPAGE_VAR_HomeAssistantURL}}:8123"
        #  key: {{HOMEPAGE_VAR_HomeAssistantAPI}}
        #  custom:



    - Homeserver:
        icon: /icons/dsm.png
        href: "https://{{HOMEPAGE_VAR_HomeserverURL}}:4600"
        description: Homeserver NAS
        ping: {{HOMEPAGE_VAR_HomeserverURL}}
        widget:
          type: diskstation
          url: "https://{{HOMEPAGE_VAR_HomeserverURL}}:4600"
          username: {{HOMEPAGE_VAR_NasUser}}
          password: {{HOMEPAGE_VAR_NASPassword}}
    - Unifi Controller:
        icon: /icons/unifi.png
        href: "https://{{HOMEPAGE_VAR_UnifiURL}}:443"
        description: Unifi Console
        ping: {{HOMEPAGE_VAR_UnifiURL}}
        widget:
          type: unifi
          url: "https://{{HOMEPAGE_VAR_UnifiURL}}"
          username: {{HOMEPAGE_VAR_NasUser}}
          password: {{HOMEPAGE_VAR_NASPassword}}

- Markets:

    - Crypto:
       # icon: /icons/crypto.png
       # href: https://coinmarketcap.com/
        #description: CoinmarketCap
        widget:
          type: coinmarketcap
          currency: GBP
          symbols: [BTC, ETH, SOL, QNT, ICP ]
          key: {{HOMEPAGE_VAR_CoinmarketcapAPI}}
          defaultinterval: 7d # Optional



