---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings
title: PJHomepage
hideVersion: true
language: en-GB
theme: dark
color: slate
headerStyle: clean
showStats: true
statusStyle: "dot"
useEqualHeights: true
hideErrors: true
layout: 
  #Auto-Discovered1:
   # style: row
    #columns: 4
  Media:
    style: row
    columns: 4
  Admin Console:
    style: row
    columns: 3
  Markets:
    style: row
    columns: 2

providers:

