networks:
   backend:
      driver: bridge

services:

   # Autoheal
   autoheal:
      restart: always
      image: willfarrell/autoheal
      environment:
         - AUTOHEAL_CONTAINER_LABEL=all
      volumes:
         - /var/run/docker.sock:/var/run/docker.sock
      networks:
         - backend

   # NGINX Proxy Manager
   nginx-proxy-manager:
      image: jc21/nginx-proxy-manager:latest
      container_name: nginx-proxy-manager
      environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
      ports:
         - 80:80
         - 443:443
         - 81:81
      volumes:
         - ${DockerDir}/nginx_pm/data:/data
         - ${DockerDir}/nginx_pm/letsencrypt:/etc/letsencrypt
         - /var/run/docker.sock:/var/run/docker.sock
      restart: always
      networks:
         - backend
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:81 || exit 1"]
         interval: 1m
         timeout: 10s
         retries: 3

   # SABNZBD
   sabnzbd:
      image: linuxserver/sabnzbd
      container_name: sabnzbd
      environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
      volumes:
         - ${DockerDir}/sabnzbd:/config
         - ${MediaDir}/downloads/complete:/downloads 
         - ${MediaDir}/downloads/incomplete:/incomplete-downloads
      ports:
         - 8080:8080
      restart: always
      networks:
         - backend
      depends_on:
         - nginx-proxy-manager
      healthcheck:
         test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
         interval: 1m
         timeout: 10s
         retries: 3

   # RADARR
   radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
         - PUID=${PUID}
         - PGID=${PGID}
         - TZ=${TZ}
      volumes:
         - ${DockerDir}/radarr:/config
         - ${MediaDir}/video/movies:/movies
         - ${MediaDir}/downloads/complete:/downloads 
      ports:
         - 7878:7878
      restart: always
      networks:
         - backend
      depends_on:
         - sabnzbd
      healthcheck:
         test