######### HomePage Dashboard ##########

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

      - HOMEPAGE_VAR_DockerURL=${HOMEPAGE_VAR_DockerURL}
      - HOMEPAGE_VAR_PJHomeserverURL=${HOMEPAGE_VAR_PJHomeserverURL}
      - HOMEPAGE_VAR_HomeAssistantURL=${HOMEPAGE_VAR_HomeAssistantURL}
      - HOMEPAGE_VAR_UnifiURL=${HOMEPAGE_VAR_UnifiURL}
      - HOMEPAGE_VAR_XOURL=${HOMEPAGE_VAR_XOURL}
      - HOMEPAGE_VAR_XCPNG1URL=${HOMEPAGE_VAR_XCPNG1URL}


      - HOMEPAGE_VAR_RadarrAPI=${HOMEPAGE_VAR_RadarrAPI}
      - HOMEPAGE_VAR_SonarrAPI=${HOMEPAGE_VAR_SonarrAPI}
      - HOMEPAGE_VAR_SabnzbAPI=${HOMEPAGE_VAR_SabnzbAPI}
      - HOMEPAGE_VAR_PlexAPI=${HOMEPAGE_VAR_PlexAPI}
      - HOMEPAGE_VAR_CoinmarketcapAPI=${HOMEPAGE_VAR_CoinmarketcapAPI}
      - HOMEPAGE_VAR_HomeAssistantAPI=${HOMEPAGE_VAR_HomeAssistantAPI}
      - HOMEPAGE_VAR_openweathermapAPI=${HOMEPAGE_VAR_openweathermapAPI}
      - HOMEPAGE_VAR_NasUser=${HOMEPAGE_VAR_NasUser}
      - HOMEPAGE_VAR_NASPassword=${HOMEPAGE_VAR_NASPassword}

    ports:
      - 3000:3000
    volumes:
      - ${DockerDir}/homepage:/app/config # Make sure your local config directory exists
      - ${DockerDir}/homepage/public/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock # (optional) For docker integrations
    restart: unless-stopped


######### VPN  ##########

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8080:8080 # sabnzb web interface
      - 8989:8989 # radarr
      - 7878:7878 # sonarr
    volumes:
      - ${DockerDir}/gluetun:/gluetun
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
    restart: unless-stopped

######### SABNZB Downloader ##########

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DockerDir}/sabnzb:/config
      - ${MediaDir}/Downloads/complete:/downloads 
      - ${MediaDir}/Downloads/incomplete:/incomplete-downloads
# Not needed as using gluetun as vpn 
#   ports:
#     - 8080:8080
    restart: unless-stopped
    depends_on: 
      - gluetun
    network_mode: service:gluetun  # we are using gluetun vpn 



######### Radarr Movie Downloads ##########

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DockerDir}/Radarr:/config
      - ${MediaDir}/Video/Movies:/movies 
      - ${MediaDir}/Downloads/complete:/downloads 
# Not needed as using gluetun as vpn 
#   ports:
#     - 7878:7878
    restart: unless-stopped
    network_mode: service:gluetun  # we are using gluetun vpn 

######### Sonarr TV Shows Downloads ##########

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${DockerDir}/Sonarr:/config
      - ${MediaDir}/Video/TV-Shows:/tv 
      - ${MediaDir}/Downloads/complete:/downloads
# Not needed as using gluetun as vpn 
#   ports:
#     - 8989:8989
    restart: unless-stopped
    network_mode: service:gluetun  # we are using gluetun vpn 



